package solution;

import java.util.List;
import java.util.ArrayList;

/**
 * This class represents one Node in the graph generated by search algorithm.
 */
public class Node {
    // Save node label
    String label;
    // Node configuration
    ArmConfig configuration;
    // Node children
    List<Node> children = new ArrayList<Node>();
}
